// <auto-generated />
using System;
using FlowWise.Services.Lancamentos.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlowWise.Services.Lancamentos.Infrastructure.Migrations
{
    [DbContext(typeof(LancamentosDbContext))]
    [Migration("20250521110537_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlowWise.Services.Lancamentos.Domain.Entities.Lancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Lancamentos", (string)null);
                });

            modelBuilder.Entity("FlowWise.Services.Lancamentos.Domain.Entities.Lancamento", b =>
                {
                    b.OwnsOne("FlowWise.Services.Lancamentos.Domain.ValueObjects.CategoriaLancamento", "Categoria", b1 =>
                        {
                            b1.Property<Guid>("LancamentoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Categoria");

                            b1.HasKey("LancamentoId");

                            b1.ToTable("Lancamentos");

                            b1.WithOwner()
                                .HasForeignKey("LancamentoId");
                        });

                    b.OwnsOne("FlowWise.Services.Lancamentos.Domain.ValueObjects.TipoLancamento", "Tipo", b1 =>
                        {
                            b1.Property<Guid>("LancamentoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Tipo");

                            b1.HasKey("LancamentoId");

                            b1.ToTable("Lancamentos");

                            b1.WithOwner()
                                .HasForeignKey("LancamentoId");
                        });

                    b.Navigation("Categoria")
                        .IsRequired();

                    b.Navigation("Tipo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
