// <auto-generated />
using System;
using FlowWise.Services.Consolidacao.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlowWise.Services.Consolidacao.Infrastructure.Migrations
{
    [DbContext(typeof(ConsolidacaoDbContext))]
    [Migration("20250521155416_ConcurrencyToken")]
    partial class ConcurrencyToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlowWise.Services.Consolidacao.Domain.Entities.SaldoDiario", b =>
                {
                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SaldoTotal")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalCreditos")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalDebitos")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Data");

                    b.ToTable("SaldosDiarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
